### ISSUE TITLE
对go.mod文件中 //indirect 和 //incompatible的解释

### ISSUE THREAD

**Issue by mikethegoblin** [pzqu/how_to_code#11]
作者您好，我最近在看您的`Go语言精进之路`电子书，我觉得很有帮助。这里我想对1.3章节提个小建议：在讲解go.mod文件时，您给的sample文件中有出现 `//indirect` 和 `//incompatible`。我想是否可以对于这两个注释进行一些讲解，读者在这里可能会想知道这两个代表什么，有什么区别。
<img width="355" alt="Screen Shot 2022-07-03 at 22 34 35" src="https://user-images.githubusercontent.com/46526613/177071641-d86a9fba-c971-49d0-a8c4-20d9a0a765e0.png">

**Comment by minibear2333** [comment]
感谢你的建议，go mod使用的包因为是自动生成的go.mod，这里没有展开说，通常我们不用在意这个，我还是会更新到我的文档中。

`incompatible` 表示不兼容标识，假如其当前版本为v3.6.0，因为其Module名字未遵循Golang所推荐的风格，即Module名中附带版本信息，我们称这个Module为不规范的Module。

在使用上没有区别，如果是我们自己开发的module，需要从 `xxx.com/xxx` 变到 `xxx.com/xxx/v2`

`indirect` 是指间接依赖的包，比如 a module 使用了 b module，但b module的go.mod不完整，或者未启用 go module的话，会把未记录在b的go.mod中又依赖了的包作为间接依赖，放到a的go.mod文件里
