### ISSUE TITLE
关于信道超时机制的建议

### ISSUE THREAD

**Issue by Ovi3** [pzqu/how_to_code#3]
[文中](https://github.com/golang-minibear2333/golang/blob/bf412225c28ec159b356dd0107b3cf0081eb9161/blog/content/4.concurrent/timeout.md)的代码，可换一种写法，简洁点：
```golang
select {
    case data := <-c:
    // do something
    case <-time.After(time.Second * 15):
}
```

**Comment by minibear2333** [comment]
> [文中](https://github.com/golang-minibear2333/golang/blob/bf412225c28ec159b356dd0107b3cf0081eb9161/blog/content/4.concurrent/timeout.md)的代码，可换一种写法，简洁点：
> 
> ```go
> select {
>     case data := <-c:
>     // do something
>     case <-time.After(time.Second * 15):
> }
> ```

感谢，这篇文章我还要再更新一下。但最种方式是本次监听动作的超时时间， 意思就说，只有在本次select 操作中会有效， 再次select 又会重新开始计时，无法保证准确定时

**Comment by Ovi3** [comment]
👌了解
