### ISSUE TITLE
关于for-range一节的建议

### ISSUE THREAD

**Issue by zbh255** [pzqu/how_to_code#7]
在讲`range`遍历的value是原值的拷贝的时候，也可以讲讲接收值的地址都是同一个，这也是一个比较常见的坑。附上: [go wiki](https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable)

原章节的[位置](https://github.com/golang-minibear2333/golang/blob/master/1.base/1-7-range%E6%B7%B1%E5%BA%A6%E8%A7%A3%E6%9E%90.md#173-%E6%9C%89%E5%8F%AF%E8%83%BD%E4%BC%9A%E9%81%87%E5%88%B0%E7%9A%84%E5%9D%91)

**Comment by minibear2333** [comment]
感谢建议，可以帮忙提个pr吗？

**Comment by zbh255** [comment]
> 感谢建议，可以帮忙提个pr吗？

pr已提
